### ISSUE TITLE
JKBigDecimal division rounds

### ISSUE THREAD

**Issue by hphu** [kirsteins/JKBigInteger#10]
JKBigDecimal doesn't scale appropriately for integer division.
Ex.
1/32 = 0, expected: 0.03125
1/1000 = 0, expected: 0.001

**Comment by Sergozh** [comment]
Hey @hphu! Did you solve it?

**Comment by hphu** [comment]
Its not really a bug its more of a precision detail. If you look at the source, it actually truncates precision if the divisor has greater precision https://github.com/kirsteins/JKBigInteger/blob/master/JKBigInteger/JKBigDecimal.m#L124-L127 so you want to either edit that code or workaround and add precision to the dividend. i.e. `1.00/3 = .33 but 1/3.00 = 0`

**Comment by Sergozh** [comment]
@hphu can you advice how to change this code to be able divide for example 1/123 = 0,008130081301? Thank you.

**Comment by Sergozh** [comment]
@hphu I can't reach result even with your example `1.00/3 = 0` for me.

**Comment by hphu** [comment]
What does your code look like?

**Comment by Sergozh** [comment]
@hphu JKBigDecimal *dec1 = [[JKBigDecimal alloc] initWithString:@"2015.987"];
    JKBigDecimal *dec2 = [[JKBigDecimal alloc] initWithString:@"5.4"];
    NSLog(@"%@ + %@ = %@", dec1, dec2, [dec1 add:dec2]);
    NSLog(@"%@ - %@ = %@", dec1, dec2, [dec1 subtract:dec2]);
    NSLog(@"%@ * %@ = %@", dec1, dec2, [dec1 multiply:dec2]);
    NSLog(@"%@ / %@ = %@", dec1, dec2, [dec1 divide:dec2]);

**Comment by hphu** [comment]
ran the same code and got `1.00 / 3 = 0.33`

**Comment by Sergozh** [comment]
@hphu and can I perform devision without .00 in the end?

**Comment by Sergozh** [comment]
@hphu still have zero. I've looked inside code and int value there I don't know how you reach 0.33

**Comment by Sergozh** [comment]
@hphu can you send me your example to skorneev@me.com? This is very important for me to be able perform division with remainder! Thank you.

**Comment by hphu** [comment]
The source looks like this:
```
    NSInteger totalFigure = figure-bigDecimal.figure;
    if (totalFigure<0) {
        NSInteger exponent = -totalFigure;
        totalFigure=0;
        JKBigInteger *mInteger = [[JKBigInteger alloc] initWithString:@"10"];
        JKBigInteger *newInteger = [mInteger pow:(unsigned int)exponent];
        bigInteger = [bigInteger multiply:newInteger];
    }
    JKBigInteger *newBigInteger = [bigInteger divide:bigDecimal.bigInteger];
    JKBigDecimal *newBigDecimal = [[JKBigDecimal alloc] initWithBigInteger:newBigInteger figure:totalFigure];
```

The result of the division takes the totalFigure as the new figure, this is the decimal places you need. 
Using the example 1.00/3
If you look it is calculated by the first decimal's figure (in the case of 1.00 it is 2) minus the second decimal's figure which is 0. The total figure = 2-0 = 2, since it is not less than 0 it is not modified further and the resulting bigDecimal should have 2 decimal places. Try to use the debugger on your code and see where the figure is changing.

**Comment by Sergozh** [comment]
@hphu can you send me your example project where I can see correct result of division?

**Comment by Sergozh** [comment]
@hphu Unfortunately I can't reach your results. Can you send me your example project? Thank you.

**Comment by hphu** [comment]
@Sergozh I was using the JKBigInteger project.

**Comment by hphu** [comment]
Closing this as it is a precision issue as I stated earlier, more of a feature than a bug

**Comment by AlbertRenshaw** [comment]
For future reference to other readers; the less accurate your dividend is, the more accurate the division answer is. (sort of). 
For example: 
3/10 will give you 0.3333333333
but...
3/10.000000 will give you 0.3
and...
3/10.000000000000 will give you 0

Kind of counter intuitive on the surface; makes sense though when you think about how the library works.
